export const ActionTypes = {
    FETCH_DATA_LOADER: 'FETCH_DATA_LOADER',
    FETCH_COUNTRIES_DATA: 'FETCH_COUNTRIES_DATA',
    FETCH_COUNTRIES_DATA_SUCCESSFULL: 'FETCH_COUNTRIES_DATA_SUCCESSFULL',
    FETCH_COUNTRY_DATA: 'FETCH_COUNTRY_DATA'
}
